### ISSUE TITLE
[BUG] (v1.50.1) - ggml-cuda.cu:5871: out of memory

### ISSUE THREAD

**Issue by SabinStargem** [LostRuins/koboldcpp#544]
I recently got an extra GPU, so I used a multi-GPU setting with KoboldCPP.  It worked fine yesterday, but now doesn't.  I also updated to the newest CUDA (12.3 update 1) this morning, which might have to do with the breakage.

My GPUs are a pair of 3060s 12gb, totaling in 24gb.  Shouldn't OOM, since my settings go for around 20gb.

With further testing:  13gb works fine.   Pushed a bit further, up to 17gb.  It worked fine.  

***
Welcome to KoboldCpp - Version 1.50.1
For command line arguments, please refer to --help
***
Attempting to use CuBLAS library for faster prompt ingestion. A compatible CuBLAS will be required.
Initializing dynamic library: koboldcpp_cublas.dll
==========
Namespace(bantokens=None, blasbatchsize=512, blasthreads=6, config=None, contextsize=16384, debugmode=0, forceversion=0, foreground=False, gpulayers=43, highpriority=False, hordeconfig=None, host='', launch=True, lora=None, model=None, model_param='C:/KoboldCPP/Models/dolphin-2_2-yi-34b.Q6_K.gguf', multiuser=True, noavx2=False, noblas=False, nommap=False, noshift=False, onready='', port=5001, port_param=5001, preloadstory=None, remotetunnel=False, ropeconfig=[0.0, 10000.0], skiplauncher=False, smartcontext=False, tensor_split=None, threads=6, useclblast=None, usecublas=['normal'], usemlock=True)
==========
Loading model: C:\KoboldCPP\Models\dolphin-2_2-yi-34b.Q6_K.gguf
[Threads: 6, BlasThreads: 6, SmartContext: False, ContextShift: True]

---
Identified as LLAMA model: (ver 6)
Attempting to Load...
---
Using automatic RoPE scaling. If the model has customized RoPE settings, they will be used directly instead!
System Info: AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 0 | VSX = 0 |
ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   maybe
ggml_init_cublas: CUDA_USE_TENSOR_CORES: maybe
ggml_init_cublas: found 2 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3060, compute capability 8.6
  Device 1: NVIDIA GeForce RTX 3060, compute capability 8.6
llama_model_loader: loaded meta data with 22 key-value pairs and 543 tensors from C:\KoboldCPP\Models\dolphin-2_2-yi-34b.Q6_K.gggヶ%〕lm_load_vocab: mismatch in special tokens definition ( 498/64000 vs 267/64000 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 64000
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: n_ctx_train      = 16384
llm_load_print_meta: n_embd           = 7168
llm_load_print_meta: n_head           = 56
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_layer          = 60
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_gqa            = 7
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: n_ff             = 20480
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 5000000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 16384
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: model type       = 30B
llm_load_print_meta: model ftype      = unknown, may not work
llm_load_print_meta: model params     = 34.39 B
llm_load_print_meta: model size       = 26.27 GiB (6.56 BPW)
llm_load_print_meta: general.name   = ehartford_dolphin-2_2-yi-34b
llm_load_print_meta: BOS token = 1 '<|startoftext|>'
llm_load_print_meta: EOS token = 7 '<|im_end|>'
llm_load_print_meta: UNK token = 0 '<unk>'
llm_load_print_meta: PAD token = 0 '<unk>'
llm_load_print_meta: LF token  = 315 '<0x0A>'
llm_load_tensors: ggml ctx size =    0.20 MiB
llm_load_tensors: using CUDA for GPU acceleration
ggml_cuda_set_main_device: using device 0 (NVIDIA GeForce RTX 3060) as main device
llm_load_tensors: mem required  = 8137.84 MiB
llm_load_tensors: offloading 43 repeating layers to GPU
llm_load_tensors: offloaded 43/63 layers to GPU
llm_load_tensors: VRAM used: 18767.82 MiB
...................................................................................................
Automatic RoPE Scaling: Using model internal value.
llama_new_context_with_model: n_ctx      = 16384
llama_new_context_with_model: freq_base  = 5000000.0
llama_new_context_with_model: freq_scale = 1
llama_new_context_with_model: kv self size  = 3840.00 MiB
llama_build_graph: non-view tensors processed: 1384/1384
llama_new_context_with_model: compute buffer total size = 1869.07 MiB
llama_new_context_with_model: VRAM scratch buffer: 1866.00 MiB
llama_new_context_with_model: total VRAM used: 20633.82 MiB (model: 18767.82 MiB, context: 1866.00 MiB)
Load Model OK: True
Embedded Kobold Lite loaded.
Starting Kobold HTTP Server on port 5001
Please connect to custom endpoint at http://localhost:5001

Input: {"n": 1, "max_context_length": 1600, "max_length": 512, "rep_pen": 1, "temperature": 0.51, "top_p": 1, "top_k": 0, "top_a": 0, "typical": 1, "tfs": 0.99, "rep_pen_range": 2048, "rep_pen_slope": 0, "sampler_order": [6, 0, 1, 3, 4, 2, 5], "memory": "", "min_p": 0.15, "genkey": "KCPP6958", "prompt": "<|im_end|>\n<|im_start|>user\nTHE FALLEN COMMANDER\n\nI died today.\n\nThere was a war, and I am one of the casualties.  Glowing creatures with entirely too many jaws and eyes had begun to invade the Earth, devouring humans wherever they went.  I am Janus, just one of many conscripts thrust into a struggle against the extinction of humanity.  Somehow, I managed to become the commander of a small squad of four people, myself included.  During one of the battles, I and my three subordinates were accosted by a particularly capable abomination.  These things are malicious, known for mutilating people alive.  To protect my comrades, I ordered them to retreat while I distracted the creature.  Moments later, the corpses of myself and the beast lay scattered across the floor of an abandoned grocery store. Feeling left my body, and the world faded away.  \n\nWith my final thoughts, I hoped those three had escaped...\n\n\nOOC: \n\nContinuing the story, describe the attempted escape of the three subordinates.  Any number may suffer terrible fates.  Any survivors should have their respective life paths explained, in terms of events, feelings, and motivations for their way of life.  Each survivor will give an ending monologue or speech about their fallen squad leader.  Their opinion of the commander may range freely.  Each character should have a name, gender, sexual orientation, and role in the squad.  They may or may not have some form of relationship with each other.  Write at least 7 paragraphs.\n\n/OOC.<|im_end|>\n<|im_start|>assistant\n", "quiet": true, "stop_sequence": ["<|im_end|>\n<|im_start|>user", "<|im_end|>\n<|im_start|>assistant"], "use_default_badwordsids": false}

Processing Prompt [BLAS] (357 / 357 tokens)
CUDA error 2 at C:\Users\HCH\Desktop\koboldcpp\ggml-cuda.cu:5871: out of memory
current device: 0

[process exited with code 1 (0x00000001)]

**Comment by LostRuins** [comment]
I just released 1.51, so try that too.

Regarding the OOM, have you tried configuring `tensor_split` ? One of the GPUs will store the KV cache so it needs more memory, so it will not be a completely even load. Also worth considering your background processes, maybe start with a clean reboot.

**Comment by LostRuins** [comment]
I think it might be worth watching task manager as the model loads, observe how the VRAM is filling up and what triggers the OOM.

Also yeah, could be your new drivers.

**Comment by LostRuins** [comment]
You select number of GPU layers to offload, then within that you can choose the ratio based on tensor split. Check the wiki for more info https://github.com/LostRuins/koboldcpp/wiki

**Comment by WarmBody** [comment]
It's funny, but an EVEN number of layers works just fine. SabinStargem, offload 42 or 44 layers.

**Comment by SabinStargem** [comment]
I tried 40, 42, and so on.   Didn't work.   Hopefully the issue is fixed up, I want to make good use of my extra GPU.

**Comment by Nexesenex** [comment]
Well, could the tensor split be calculated automatically at launch?

Example :

GPU0VRAM_in_MB, minus pre-launch-VRAM-occupation_in_MB (desktop), minus CTX_required_VRAM_in_MB, minus other VRAM occupations bound to GPU0 (Blast batch buffer?) -> first tensor split number

GPU1VRAM_in_MB, minus pre-launch-VRAM-occupation -> second tensor split number

With maybe an adequate rounding so it leaves a margin to avoid OOM on one of the cards due to the various tensors size.


Also, in a multi-GPU setting, could the KV cache of each layer be loaded on the GPU said layer is loaded on to rationalize things? And in such case, would it boost performances as it's already the case now in a partial offload on GPU when the kv cache of each layer (and only those) are loaded along the layer itself on the GPU?
