### ISSUE TITLE
Koboldcpp 1.55: ERROR: ggml-cuda was compiled without support for the current GPU architecture.

### ISSUE THREAD

**Issue by Spacellary** [LostRuins/koboldcpp#610]
Since updating from 1.54 to 1.55 I've been getting `ERROR: ggml-cuda was compiled without support for the current GPU architecture.` errors, This only happens with 1.55 and not 1.54, running on Windows 11, GPU: NVIDIA GeForce GTX 1070 Ti (8GB, Pascal), Drivers: 546.33 (latest currently).

Related to "Switched cuda pool malloc back to the old implementation" from the 1.55 release changelog?

Log:
##### 1.54:
```
koboldcpp "C:\koboldcpp\models\testing\kunoichi-7b.Q5_K_S.gguf" --multiuser --gpulayers 33 --contextsize 4096 --port 6969 --usecublas --quiet --remotetunnel # --smartcontext
***
Welcome to KoboldCpp - Version 1.54
Attempting to use CuBLAS library for faster prompt ingestion. A compatible CuBLAS will be required.
Initializing dynamic library: koboldcpp_cublas.dll
==========
Namespace(bantokens=None, blasbatchsize=512, blasthreads=5, config=None, contextsize=4096, debugmode=0, forceversion=0, foreground=False, gpulayers=33, highpriority=False, hordeconfig=None, host='', launch=False, lora=None, model=None, model_param='C:\\\koboldcpp\\models\\testing\\kunoichi-7b.Q5_K_S.gguf', multiuser=1, noavx2=False, noblas=False, nommap=False, noshift=False, onready='', port=6969, port_param=5001, preloadstory='', quiet=True, remotetunnel=True, ropeconfig=[0.0, 10000.0], skiplauncher=False, smartcontext=False, ssl=None, tensor_split=None, threads=5, useclblast=None, usecublas=[], usemlock=False)
==========
Loading model: C:\koboldcpp\models\testing\kunoichi-7b.Q5_K_S.gguf
[Threads: 5, BlasThreads: 5, SmartContext: False, ContextShift: True]

The reported GGUF Arch is: llama

---
Identified as LLAMA model: (ver 6)
Attempting to Load...
---
Using automatic RoPE scaling. If the model has customized RoPE settings, they will be used directly instead!
System Info: AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 0 | VSX = 0 |
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce GTX 1070 Ti, compute capability 6.1, VMM: yes
llama_model_loader: loaded meta data with 23 key-value pairs and 291 tensors from C:\koboldcpp\models\testing\kO¬:¡Zþllm_load_vocab: special tokens definition check successful ( 259/32000 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 32000
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: n_ctx_train      = 8192
llm_load_print_meta: n_embd           = 4096
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_gqa            = 4
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: n_ff             = 14336
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 10000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 8192
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: model type       = 7B
llm_load_print_meta: model ftype      = unknown, may not work
llm_load_print_meta: model params     = 7.24 B
llm_load_print_meta: model size       = 4.65 GiB (5.52 BPW)
llm_load_print_meta: general.name     = sanjiwatsuki_kunoichi-7b
llm_load_print_meta: BOS token        = 1 '<s>'
llm_load_print_meta: EOS token        = 2 '</s>'
llm_load_print_meta: UNK token        = 0 '<unk>'
llm_load_print_meta: LF token         = 13 '<0x0A>'
llm_load_tensors: ggml ctx size       =    0.11 MiB
llm_load_tensors: using CUDA for GPU acceleration
llm_load_tensors: system memory used  =   86.05 MiB
llm_load_tensors: VRAM used           = 4679.55 MiB
llm_load_tensors: offloading 32 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 33/33 layers to GPU
...................................................................................................
Automatic RoPE Scaling: Using (scale:1.000, base:10000.0).
llama_new_context_with_model: n_ctx      = 4176
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init: VRAM kv self = 522.00 MB
llama_new_context_with_model: KV self size  =  522.00 MiB, K (f16):  261.00 MiB, V (f16):  261.00 MiB
llama_build_graph: non-view tensors processed: 676/676
llama_new_context_with_model: compute buffer total size = 296.35 MiB
llama_new_context_with_model: VRAM scratch buffer: 293.16 MiB
llama_new_context_with_model: total VRAM used: 5494.71 MiB (model: 4679.55 MiB, context: 815.16 MiB)
Load Model OK: True
Embedded Kobold Lite loaded.
Downloading Cloudflare Tunnel for Windows...
======
Please connect to custom endpoint at http://localhost:6969
Starting Cloudflare Tunnel for Windows, please wait...
Your remote Kobold API can be found at https://cute-thoroughly-martial-march.trycloudflare.com/api
Your remote OpenAI Compatible API can be found at https://cute-thoroughly-martial-march.trycloudflare.com/v1
======

Your remote tunnel is ready, please connect to https://cute-thoroughly-martial-march.trycloudflare.com
```
##### Switching to 1.55 with `scoop reset koboldcpp@1.55`...

```
koboldcpp "C:\koboldcpp\models\testing\kunoichi-7b.Q5_K_S.gguf" --multiuser --gpulayers 33 --contextsize 4096 --port 6969 --usecublas --quiet --remotetunnel # --smartcontext
***
Welcome to KoboldCpp - Version 1.55
Attempting to use CuBLAS library for faster prompt ingestion. A compatible CuBLAS will be required.
Initializing dynamic library: koboldcpp_cublas.dll
==========
Namespace(bantokens=None, blasbatchsize=512, blasthreads=5, config=None, contextsize=4096, debugmode=0, forceversion=0, foreground=False, gpulayers=33, highpriority=False, hordeconfig=None, host='', launch=False, lora=None, model=None, model_param='C:\\\koboldcpp\\models\\testing\\kunoichi-7b.Q5_K_S.gguf', multiuser=1, noavx2=False, noblas=False, nommap=False, noshift=False, onready='', port=6969, port_param=5001, preloadstory='', quiet=True, remotetunnel=True, ropeconfig=[0.0, 10000.0], skiplauncher=False, smartcontext=False, ssl=None, tensor_split=None, threads=5, useclblast=None, usecublas=[], usemlock=False)
==========
Loading model: C:\koboldcpp\models\testing\kunoichi-7b.Q5_K_S.gguf
[Threads: 5, BlasThreads: 5, SmartContext: False, ContextShift: True]

The reported GGUF Arch is: llama

---
Identified as LLAMA model: (ver 6)
Attempting to Load...
---
Using automatic RoPE scaling. If the model has customized RoPE settings, they will be used directly instead!
System Info: AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 0 | VSX = 0 |
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce GTX 1070 Ti, compute capability 6.1, VMM: yes
llama_model_loader: loaded meta data with 23 key-value pairs and 291 tensors from C:\koboldcpp\models\testing\kû S'45llm_load_vocab: special tokens definition check successful ( 259/32000 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 32000
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: n_ctx_train      = 8192
llm_load_print_meta: n_embd           = 4096
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 4
llm_load_print_meta: n_embd_k_gqa     = 1024
llm_load_print_meta: n_embd_v_gqa     = 1024
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: n_ff             = 14336
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 10000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 8192
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: model type       = 7B
llm_load_print_meta: model ftype      = unknown, may not work
llm_load_print_meta: model params     = 7.24 B
llm_load_print_meta: model size       = 4.65 GiB (5.52 BPW)
llm_load_print_meta: general.name     = sanjiwatsuki_kunoichi-7b
llm_load_print_meta: BOS token        = 1 '<s>'
llm_load_print_meta: EOS token        = 2 '</s>'
llm_load_print_meta: UNK token        = 0 '<unk>'
llm_load_print_meta: LF token         = 13 '<0x0A>'
llm_load_tensors: ggml ctx size       =    0.11 MiB
llm_load_tensors: using CUDA for GPU acceleration
llm_load_tensors: system memory used  =   86.05 MiB
llm_load_tensors: VRAM used           = 4679.55 MiB
llm_load_tensors: offloading 32 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 33/33 layers to GPU
...................................................................................................
Automatic RoPE Scaling: Using (scale:1.000, base:10000.0).
llama_new_context_with_model: n_ctx      = 4176
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init: VRAM kv self = 522.00 MB
llama_new_context_with_model: KV self size  =  522.00 MiB, K (f16):  261.00 MiB, V (f16):  261.00 MiB
llama_build_graph: non-view tensors processed: 676/676
llama_new_context_with_model: compute buffer total size = 296.35 MiB
llama_new_context_with_model: VRAM scratch buffer: 293.16 MiB
llama_new_context_with_model: total VRAM used: 5494.71 MiB (model: 4679.55 MiB, context: 815.16 MiB)
ERROR: ggml-cuda was compiled without support for the current GPU architecture.
ERROR: ggml-cuda was compiled without support for the current GPU architecture.
ERROR: ggml-cuda was compiled without support for the current GPU architecture.
(...)
ERROR: ggml-cuda was compiled without support for the current GPU architecture.
ERROR: ggml-cuda was compiled without support for the current GPU architecture.
ERROR: ggml-cuda was compiled without support for the current GPU architecture.
CUDA error: CUBLAS_STATUS_EXECUTION_FAILED
  current device: 0, in function ggml_cuda_op_mul_mat_cublas at d:\a\koboldcpp\koboldcpp\ggml-cuda.cu:7856
  cublasSgemm_v2(g_cublas_handles[id], CUBLAS_OP_T, CUBLAS_OP_N, row_diff, src1_ncols, ne10, &alpha, src0_ddf_i, ne00, src1_ddf1_i, ne10, &beta, dst_dd_i, ldc)
GGML_ASSERT: d:\a\koboldcpp\koboldcpp\ggml-cuda.cu:226: !"CUDA error"                                                                                        
```

#### Windows 11 - Using prebuilt executable.

**Comment by intulint** [comment]
Yes, too. 1.55, cublas, nvidia1050ti

```
ERROR: ggml-cuda was compiled without support for the current GPU architecture.
ERROR: ggml-cuda was compiled without support for the current GPU architecture.
CUDA error: CUBLAS_STATUS_EXECUTION_FAILED
  current device: 0, in function ggml_cuda_op_mul_mat_cublas at d:\a\koboldcpp\koboldcpp\ggml-cuda.cu:7856
  cublasSgemm_v2(g_cublas_handles[id], CUBLAS_OP_T, CUBLAS_OP_N, row_diff, src1_ncols, ne10, &alpha, src0_ddf_i, ne00, src1_ddf1_i, ne10, &beta, dst_dd_i, ldc)
GGML_ASSERT: d:\a\koboldcpp\koboldcpp\ggml-cuda.cu:226: !"CUDA error"
```

**Comment by ContinuumOperand** [comment]
It seems that even the Colab is broken.
Logs:
https://hastebin.com/share/xiramixizu.bash

**Comment by Vladonai** [comment]
Win10 and RTX3050 everything is OK. I'd also like to point out that the initial context processing is noticeably faster compared to 1.54.

I'm implying that "putting things back the way they were" is not the best option :)

**Comment by frammiie** [comment]
Can confirm same issue, doesn't occur on 1.54

**Comment by Spacellary** [comment]
> Can confirm same issue, doesn't occur on 1.54

Can you tell us what is your GPU?

**Comment by DrVonSinistro** [comment]
Same issue here with 2 Pascal cards (Tesla P40)

**Comment by KraiiFox** [comment]
+1 having the issue here too. Also using pascal, gtx 1070.

**Comment by LostRuins** [comment]
I'm assuming all those having issues are running the 1.55 cuda windows prebuilt exe?

**Comment by Spacellary** [comment]
> I'm assuming all those having issues are running the 1.55 cuda windows prebuilt exe?

Yes. Pretty much. And using Pascal cards it seems. I'm using the prebuilt.

**Comment by LostRuins** [comment]
Can you see if 1.55.1 fixes this? I don't have a pascal card so I can't test myself.

**Comment by Spacellary** [comment]
@LostRuins Seems to be working as expected now. Thanks for the quick work.

```
koboldcpp "C:\koboldcpp\models\testing\Loyal-Toppy-Bruins-Maid-DARE-7B-q4_k.gguf" --multiuser --gpulayers 33 --contextsize 4096 --port 6969 --usecublas --quiet --remotetunnel
***
Welcome to KoboldCpp - Version 1.55.1
Attempting to use CuBLAS library for faster prompt ingestion. A compatible CuBLAS will be required.
Initializing dynamic library: koboldcpp_cublas.dll
==========
Namespace(bantokens=None, blasbatchsize=512, blasthreads=5, config=None, contextsize=4096, debugmode=0, forceversion=0, foreground=False, gpulayers=33, highpriority=False, hordeconfig=None, host='', launch=False, lora=None, model=None, model_param='C:\\\koboldcpp\\models\\testing\\Loyal-Toppy-Bruins-Maid-DARE-7B-q4_k.gguf', multiuser=1, noavx2=False, noblas=False, nommap=False, noshift=False, onready='', port=6969, port_param=5001, preloadstory='', quiet=True, remotetunnel=True, ropeconfig=[0.0, 10000.0], skiplauncher=False, smartcontext=False, ssl=None, tensor_split=None, threads=5, useclblast=None, usecublas=[], usemlock=False)
==========
Loading model: C:\koboldcpp\models\testing\Loyal-Toppy-Bruins-Maid-DARE-7B-q4_k.gguf
[Threads: 5, BlasThreads: 5, SmartContext: False, ContextShift: True]

The reported GGUF Arch is: llama

---
Identified as LLAMA model: (ver 6)
Attempting to Load...
---
Using automatic RoPE scaling. If the model has customized RoPE settings, they will be used directly instead!
System Info: AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 0 | VSX = 0 |
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce GTX 1070 Ti, compute capability 6.1, VMM: yes
llama_model_loader: loaded meta data with 23 key-value pairs and 291 tensors from C:\koboldcpp\models\testing\LXLBsllm_load_vocab: special tokens definition check successful ( 259/32000 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 32000
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: n_ctx_train      = 32768
llm_load_print_meta: n_embd           = 4096
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 4
llm_load_print_meta: n_embd_k_gqa     = 1024
llm_load_print_meta: n_embd_v_gqa     = 1024
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: n_ff             = 14336
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 10000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 32768
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: model type       = 7B
llm_load_print_meta: model ftype      = unknown, may not work
llm_load_print_meta: model params     = 7.24 B
llm_load_print_meta: model size       = 4.07 GiB (4.83 BPW)
llm_load_print_meta: general.name     = text-generation-webui-main\models
llm_load_print_meta: BOS token        = 1 '<s>'
llm_load_print_meta: EOS token        = 2 '</s>'
llm_load_print_meta: UNK token        = 0 '<unk>'
llm_load_print_meta: LF token         = 13 '<0x0A>'
llm_load_tensors: ggml ctx size       =    0.11 MiB
llm_load_tensors: using CUDA for GPU acceleration
llm_load_tensors: system memory used  =   70.42 MiB
llm_load_tensors: VRAM used           = 4095.05 MiB
llm_load_tensors: offloading 32 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 33/33 layers to GPU
.................................................................................................
Automatic RoPE Scaling: Using (scale:1.000, base:10000.0).
llama_new_context_with_model: n_ctx      = 4176
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init: VRAM kv self = 522.00 MB
llama_new_context_with_model: KV self size  =  522.00 MiB, K (f16):  261.00 MiB, V (f16):  261.00 MiB
llama_build_graph: non-view tensors processed: 676/676
llama_new_context_with_model: compute buffer total size = 296.35 MiB
llama_new_context_with_model: VRAM scratch buffer: 293.16 MiB
llama_new_context_with_model: total VRAM used: 4910.21 MiB (model: 4095.05 MiB, context: 815.16 MiB)
Load Model OK: True
Embedded Kobold Lite loaded.
Cloudflared file exists, reusing it...
======
Please connect to custom endpoint at http://localhost:6969
Starting Cloudflare Tunnel for Windows, please wait...
Your remote Kobold API can be found at https://comparisons-jury-page-land.trycloudflare.com/api
Your remote OpenAI Compatible API can be found at https://comparisons-jury-page-land.trycloudflare.com/v1
======

Your remote tunnel is ready, please connect to https://comparisons-jury-page-land.trycloudflare.com
```

**Comment by LostRuins** [comment]
Thanks for reporting the issue.

**Comment by LostRuins** [comment]
Btw @henk717 I think this is caused by trying to target `all-major` as opposed to explicitly indicating the cuda arch, not sure if the linux builds will have similar issues on Pascal. 

That was the main thing I reverted. Something about the way it's set causes the compute capability definitions to not match their expected values which triggers an assert: see https://github.com/ggerganov/llama.cpp/pull/4556

**Comment by KraiiFox** [comment]
![Screenshot 2024-01-11 132239](https://github.com/LostRuins/koboldcpp/assets/43300558/899bec30-b2b9-402c-8e19-3ef8dc8090f4)

**Comment by KraiiFox** [comment]
Can confirm it is indeed working on Window.
![Screenshot 2024-01-11 132239](https://github.com/LostRuins/koboldcpp/assets/43300558/7a9aecc9-489b-4878-b8da-1ee69ab9c6be)



> Btw @henk717 I think this is caused by trying to target `all-major` as opposed to explicitly indicating the cuda arch, not sure if the linux builds will have similar issues on Pascal.
> 
> That was the main thing I reverted. Something about the way it's set causes the compute capability definitions to not match their expected values which triggers an assert: see [ggerganov#4556](https://github.com/ggerganov/llama.cpp/pull/4556)

Ha, was just about the mention that it is still an issue in Linux. https://github.com/LostRuins/koboldcpp/discussions/604

**Comment by DrVonSinistro** [comment]
Tesla P40 here; its working again with 1.55.1 !

**Comment by Pepice23** [comment]
GTX1060 6GB 1.55.1 works fine thank you!

**Comment by intulint** [comment]
Yep, it works now

**Comment by frammiie** [comment]
@LostRuins Yep totally fixed, thank you so much for your swift work and supporting older architectures! <3

**Comment by ContinuumOperand** [comment]
Glad to see it seems to be fixed for everyone affected. Thanks again @LostRuins!

**Comment by ContinuumOperand** [comment]
Glad to see it seems to be fixed for everyone affected. Thanks @LostRuins!

**Comment by TheTerrasque** [comment]
```
Welcome to KoboldCpp - Version 1.55.1
Attempting to use CuBLAS library for faster prompt ingestion. A compatible CuBLAS will be required.
---
System Info: AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 |
ggml_init_cublas: found 1 CUDA devices:
  Device 0: Tesla P40, compute capability 6.1, VMM: yes
---
llama_new_context_with_model: compute buffer total size = 282.10 MiB
llama_new_context_with_model: VRAM scratch buffer: 278.91 MiB
llama_new_context_with_model: total VRAM used: 10113.80 MiB (model: 9585.52 MiB, context: 528.29 MiB)
ERROR: ggml-cuda was compiled without support for the current GPU architecture.
ERROR: ggml-cuda was compiled without support for the current GPU architecture.
ERROR: ggml-cuda was compiled without support for the current GPU architecture.
```

Linux, precompiled from release page.

**Comment by Spacellary** [comment]
@TheTerrasque 
> Linux, precompiled from release page.
> 
> Edit: This seems to be a possibly separate issue, as I see the same on 1.54

Probably this?
https://github.com/LostRuins/koboldcpp/discussions/604
I experienced the same issue even in WSL2.

@LostRuins Can the same solution be applied to the Linux prebuilt package as the Windows one? It seems to have solved it.

**Comment by TheTerrasque** [comment]
Possibly. On a side note, I got it working by compiling the code with `make LLAMA_OPENBLAS=1 LLAMA_CLBLAST=1 LLAMA_CUBLAS=1 CUDA_DOCKER_ARCH=compute_61` - so it works if one specifies the card architecture directly.

**Comment by Spacellary** [comment]
@TheTerrasque - Yes, it seems using `all-major` is causing it.

**Comment by LostRuins** [comment]
May be Related: https://github.com/ggerganov/llama.cpp/issues/5046

**Comment by LostRuins** [comment]
Hi, can you try 1.56? Should be fixed now

**Comment by Spacellary** [comment]
For the Windows prebuilt it was fixed since 1.55.1 and I can confirm that it's now working under WSL2 with the Linux prebuilt as well. Thanks for the dedicated work, @LostRuins. You're doing more than you can imagine for this community.

Using 1.56 prebuilt executables under:
* **❑ Ubuntu** in **❑ WSL2** - Success
* **❑ Windows 11** - Success

`GPU: GTX 1070 Ti 8GB (Pascal)`

**Comment by TheTerrasque** [comment]
Can confirm compiled release 1.56 works on p40 on ubuntu linux :)
